project_id = "ohwtbkudpkfbakynikyj"

[functions.aggregate-weather]
verify_jwt = true

[functions.ai-weather-insights]
verify_jwt = true

[functions.fetch-moon-data]
verify_jwt = true

[functions.generate-landmark-image]
verify_jwt = true

[functions.send-feedback]
verify_jwt = true

[functions.verify-predictions]
verify_jwt = false

[functions.process-weather-corrections]
verify_jwt = false

